#FROM php:5
#
#RUN apt-get update && apt-get install -y unzip libmemcached-dev zlib1g-dev
#RUN .Docker-php-ext-install mysqli pdo_mysql
#RUN pecl install memcached-2.2.0 && .Docker-php-ext-enable memcached
#RUN curl -sS https://getcomposer.org/installer | php; mv composer.phar /usr/local/bin/composer ; mkdir /var/dev
#
#RUN mkdir /var/www && mkdir /var/www/html
#
#
#WORKDIR /var/www/html
#
#CMD ["bash"]